/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pw.proz;

public class App {
    public String getGreeting() {
        return "You lose!";
    }

    public static void main(String[] args) {

        Display myDisplay = new Display();
        
        boolean lose = false;
        while (!lose) {
            myDisplay.grp.atkr.move(myDisplay.grp.my_base);

            if (!myDisplay.grp.my_base.isBaseDown())
                myDisplay.grp.atkr.attack(myDisplay.grp.my_base);
            else {
                lose = true;
            }

            myDisplay.grp.repaint();
            try { Thread.sleep(10); } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        System.out.println(new App().getGreeting());

    }
}
