/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pw.proz;

import Entity.*;

import java.awt.*;


public class App {

    private static Base myBase = new Base(6, 6);
    private static Spawn mySpawn = new Spawn(1, 1);
    public static int Rows = 15;
    public static final int Columns = 26;

    private static GameLoop gameLoop;
    private static Graphics graphic;
    private static Display myDisplay;

    public static GameLoop getGameLoop() {
        return gameLoop;
    }

    public static Base getBase() {
        return myBase;
    }

    public static Spawn getSpawn() {
        return mySpawn;
    }

    public static Display getDisplay() {
        return myDisplay;
    }

    public String getGreeting() {
        return "You lose!";
    }

    public App() {

    }

    public static void main(String[] args) {

        gameLoop = new GameLoop();
        myDisplay = new Display();
        graphic = myDisplay.graphic.getGraphics();


        gameLoop.run(myDisplay, myBase, mySpawn);

        System.out.println(new App().getGreeting());

    }

    public static void handleLeftClick(int mouseX, int mouseY) {
        System.out.println("Handling mouse click " + mouseX + " " + mouseY);
        Rectangle board = new Rectangle(40, 40, 40 * Columns, 40 * Rows);
        Point tile = new Point(0, 0);

        if (board.contains(mouseX, mouseY)) {
            tile = new Point((mouseX) / 40, (mouseY) / 40);
            System.out.println(gameLoop.getCurrentTile() + " " + tile + " " + gameLoop.getCurrentTile().equals(tile));
            if (gameLoop.getCurrentTile().equals(tile))
                gameLoop.setCurrentTile(new Point(0, 0));
            else
                gameLoop.setCurrentTile(tile);
        }
        System.out.println(gameLoop.getCurrentTile());
    }

}