/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pw.proz;

import java.awt.*;
import java.awt.image.ImageObserver;
import java.text.AttributedCharacterIterator;

public class App {

    private static Enemy myEnemy = new Enemy(15, 16);
    private static Base myBase = new Base(6, 6);
    private static TowerArmor myTower = new TowerArmor(1,55,15,5);
    private static GameLoop gameLoop = new GameLoop();

    public static GameLoop getGameLoop() {
        return gameLoop;
    }

    public static Enemy getEnemy() {
        return myEnemy;
    }

    public static Base getBase() {
        return myBase;
    }

    public static Tower getTower() {
        return myTower;
    }

    public String getGreeting() {
        return "You lose!";
    }

    public static void main(String[] args) {

        Display myDisplay = new Display();
        Graphics graphic = myDisplay.graphic.getGraphics();



        gameLoop.run(myDisplay, myEnemy, myTower, myBase);


        System.out.println(new App().getGreeting());

    }
}
